### ISSUE TITLE
Array should provide customizable `Add` button text, as acronyms are incorrectly translated

### ISSUE THREAD

**Issue by lirwin** [ciena-frost/ember-frost-bunsen#506]
see: http://ciena-frost.github.io/ember-frost-bunsen/#/examples?model=array&view=array

 ```
"children": [
        {
          "model": "name",
          "extends": "name"
        },
        {
          "model": "addresses",
          "arrayOptions": {
            "itemCell": {
              "extends": "addr",
              "label": "Address"
            }
          }
        }
      ]
```

I cannot find a way to customize the array `Add` button text, here are some of the issues:

![array-add-label-issue2](https://user-images.githubusercontent.com/4720276/35419743-984e803c-01ee-11e8-9fff-ca544cf55b51.png)

![array-add-label-issue1](https://user-images.githubusercontent.com/4720276/35419742-983307bc-01ee-11e8-9f89-b4d2d5d0357f.png)

**Comment by gkchestertron** [comment]
Yeah. That's goofy.

**Comment by notmessenger** [comment]
With minimum configuration:
  * the title of the section is the capitalized value of the `model` property in the `children` definition.
  * the button label is the lowercased and singularized value of the `model` property in the `children` definition prefixed with the text of "Add ".

So given this data:

```
main: {
  children: [
    {
      model: 'name',
      extends: 'name'
    },
    {
      model: 'addresses',
      arrayOptions: {
        itemCell: {
          extends: 'addr',
          label: 'Address'
        }
      }
    }
  ]
}
```

the section title is "Addresses" and the button text is "Add address"


When setting the "label" property in the configuration:
  * the title of the section is the exact value of the `model` property in the `children` definition.
  * the button label is the lowercased and singularized value of the `model` property in the `children` definition prefixed with the text of "Add ".

So given this data:

```
main: {
  children: [
    {
      model: 'name',
      extends: 'name'
    },
    {
      model: 'addresses',
      label: 'IP Addresses',
      arrayOptions: {
        itemCell: {
          extends: 'addr',
          label: 'Address'
        }
      }
    }
  ]
}
```

the section title is "IP Addresses" and the button text is "Add ip address"


This issue requests being able to have more control over the text that appears for the button label, so what should the behavior described above be changed to?  Should the button text become the singularized value of the provided "label" property *without* being lowercased so that in the example of the value "IP Addresses" being provided the button label would become "Add IP Address"?

If this is what is chosen - or something else - keep in mind that this is going to change this behavior across the board for anytime a value is provided for the "label" property so regardless of whether this is considered a MAJOR change or not, is this the behavior we wish to adopt wholesale?

**Comment by notmessenger** [comment]
JIRA: FROST-1237

**Comment by lirwin** [comment]
not lowercasing, i.e.  "Add IP Address" will not work.  

- can we add a new prop, like`buttonText`, which will override automatic `Add ...` button text generation?
- if consumer provides `buttonText: 'Add FOO here please'` then button will say 'Add FOO here please'.  
- this gives consumer flexibility in case they don't want `Add` at all...maybe they want button to say 'New address' or whatever

**Comment by notmessenger** [comment]
Why will

> not lowercasing, i.e. "Add IP Address" will not work.

not work?  Isn't that what this issue is asking for, that the text not be changed to `ip...` like it is now?


> can we add a new prop, likebuttonText, which will override automatic Add ... button text generation?

From a development standpoint this can be done obviously, but right now the behavior is that the model name becomes the section title and the text on the button.  If the `label` property is populated then it becomes the section title and the text on the button.  When a new property is populated - as you have proposed - what is used for display of the section title?  The model name still, but use the `label` property if it's populated?  The existing implementation is designed to cut down on the amount of configuration required and adding an additional property that only controls the text of the button but not the section title is adding complexity.  I'm not saying we can't do it, I'm just saying we need to keep that in mind when deciding how to we want to approach this problem.  For the record, the proposal in https://github.com/ciena-frost/ember-frost-bunsen/issues/506#issuecomment-362084942 will keep the text of the section title and button in sync.
