### ISSUE TITLE
deal with a cancel click and not show validation errors

### ISSUE THREAD

**Issue by rox163** [ciena-frost/ember-frost-bunsen#87]
open a dialog and the first input gets focus. when you dismiss the dialog, via cancel button, that triggers the validation because the Input loses focus, which then shows the error message for a fraction of a second before the dialog transitions out. It should not show the validation error if the dialog is being cancelled. Maybe bunsen should accept some kind of flag from the app, indicating that the dialog is being cancelled so don't run the validations.

**Comment by job13er** [comment]
Just to point out some of the discussion @sglanzer and I had about this, it's slightly tricky because the `blur` event on the input will fire before the `click` on the cancel button, so the app wouldn't know, at the time the `blur` event is fired, that the user wants to close the form. We may be able to do something with deferring the validation to the next run loop, or something along those lines so that the app has a chance to tell bunsen not to display the validation. Either that, or we could have bunsen not actually display the validation errors at all, and it just triggers the `onValidation`, then the consumer would be responsible for passing in any errors it wants bunsen to display, this would give the calling context a chance to intercept any validation errors and not display them in whatever scenarios may be appropriate to withhold that visualization.

**Comment by rox163** [comment]
This is definitely a usability problem that will be raised soon because another issue here is when the user clicks Cancel a little too high on the button, the validation kicks in, shifting the button down a bit. When the mouse click is released, it isnt on the button anymore, so the dialog stays open. The user has to click on Cancel again to close it.
FYI A fix for this issue will be expected in MCP by May end.
